# run: conda env create --file environment.yml
name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - anaconda
  - pandas
  - numpy
  - ipykernel
  - nb_conda_kernels
  - jupyter
  - transformers
  - spacy # with conda-forge
  - pip
  - pip:
      - sentence-transformers
      - bertopic
      - wikipedia-api # pip3
      - top2vec
      - gensim
      - nltk
      - imblearn # pip3

