# run: conda env create --file environment.yml
name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - anaconda
  - numpy
  - jupyter
  - ipykernel
  - nb_conda_kernels
  - transformers
  - spacy # with conda-forge
  - pip
  - pip:
      - sentence-transformers
      - bertopic
      - wikipedia-api
      - top2vec
      - gensim
      - nltk
      - imblearn
      - matplotlib
      - pandas


