# run: conda env create --file environment.yml
name: thesis
dependencies:
  - python=3.9
  - anaconda
  - pandas
  - numpy
  - ipykernel
  - nb_conda_kernels
  - jupyter
  - transformers
  - pip
  - pip:
      - sentence-transformers
      - bertopic
      - Wikipedia-API
      - top2vec
      - gensim
      - nltk

