# run: conda env create --file environment.yml
name: thesis
dependencies:
  - python=3.9
  - anaconda
  - numpy
  - jupyter
  - ipykernel
  - nb_conda_kernels
  - transformers
  - spacy
  - pip
  - pip:
      - sentence-transformers
      - bertopic
      - wikipedia-api
      - top2vec
      - gensim
      - nltk
      - imblearn
      - matplotlib
      - pandas

# conda install pytorch torchvision torchaudio -c pytorch
# conda install faiss-cpu -c pytorch


